# Generated by Django 5.1.2 on 2024-11-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_location_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address_line2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
