# Generated by Django 5.1.2 on 2024-12-05 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_location_profile_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='distric',
            new_name='district',
        ),
    ]
